### ISSUE TITLE
How to scan bots

### ISSUE THREAD

**Issue by KaNNabysX** [i-am-unbekannt/AXIS#2]
How to scan bots on the cnc and how to load them

**Comment by i-am-unbekannt** [comment]
Hello KaNNabysX,

I am currently working on the new version of the Unbekannt Framework. However, I had planned to create a newer version of the AXIS botnet much earlier. This version will have an option to automatically scan the bots to the CNC. Until then, you will need to educate yourself how to scan bots to the CNC. From my personal experience, I know that there are scripts available on GitHub that can make this process possible.

~ Unbekannt

**Comment by i-am-unbekannt** [comment]
Hello KaNNabysX,

I am currently working on the new version of the Unbekannt Framework. However, I had planned to create a newer version of the AXIS botnet much earlier. This version will have an option to automatically scan the bots to the CNC. Until then, you will need to educate yourself how to scan bots to the CNC. From my personal experience, I know that there are scripts available on GitHub that can make this process possible.

~ Unbekannt

**Comment by KaNNabysX** [comment]
Alright, thanks man and keep up the good work with everything you do.
