### ISSUE TITLE
Hi how to use command to attack?

### ISSUE THREAD

**Issue by anonsecbotnetstudent123** [i-am-unbekannt/AXIS#4]
! STOMP   [IP] [PORT] [TIME] 32 [FLAGS(ALL)] 10 1024
Like that command i can understand STOMP   [IP] [PORT] [TIME] but i can't understand this 32 [FLAGS(ALL)] 10 1024?

**Comment by i-am-unbekannt** [comment]
Hello anonsecbotnetstudent123,

The value "32" means that you need to specify 32 flags for the command. The phrase "[FLAGS(ALL)]" suggests that you should include all available flags (32). Lastly, the values "10" and "1024" at the end are additional variables that you need to provide based on your input.

~ Unbekannt
