### ISSUE TITLE
i get this error

### ISSUE THREAD

**Issue by MadaraV2492** [i-am-unbekannt/AXIS#5]
AXIS_CNC.c: In function ‘BotEventLoop’:
AXIS_CNC.c:177:7: warning: passing argument 1 of ‘fprintf’ discards ‘volatile’ qualifier from pointer target type [enabled by default]
       fprintf(telFD, "%s\n", line);
       ^
In file included from AXIS_CNC.c:1:0:
/usr/include/stdio.h:356:12: note: expected ‘struct FILE * __restrict__’ but argument is of type ‘volatile struct FILE *’
 extern int fprintf (FILE *__restrict __stream,
            ^
AXIS_CNC.c:178:7: warning: passing argument 1 of ‘fflush’ discards ‘volatile’ qualifier from pointer target type [enabled by default]
       fflush(telFD);
       ^
In file included from AXIS_CNC.c:1:0:
/usr/include/stdio.h:242:12: note: expected ‘struct FILE *’ but argument is of type ‘volatile struct FILE *’
 extern int fflush (FILE *__stream);
            ^
AXIS_CNC.c: In function ‘BotWorker’:
AXIS_CNC.c:276:15: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  int datafd = (int)sock;
               ^
AXIS_CNC.c: In function ‘TitleWriter’:
AXIS_CNC.c:341:15: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  int datafd = (int)sock;
               ^
AXIS_CNC.c: In function ‘BotListener’:
AXIS_CNC.c:690:52: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
         pthread_create( &thread, NULL, &BotWorker, (void *)newsockfd);
                                                    ^
AXIS_CNC.c: In function ‘main’:
AXIS_CNC.c:736:9: warning: passing argument 3 of ‘pthread_create’ from incompatible pointer type [enabled by default]
         pthread_create(&thread[0], NULL, &BotListener, port);
         ^
In file included from AXIS_CNC.c:16:0:
/usr/include/pthread.h:235:12: note: expected ‘void * (*)(void *)’ but argument is of type ‘void * (*)(int)’
 extern int pthread_create (pthread_t *__restrict __newthread,
            ^
AXIS_CNC.c:736:9: warning: passing argument 4 of ‘pthread_create’ makes pointer from integer without a cast [enabled by default]
         pthread_create(&thread[0], NULL, &BotListener, port);
         ^
In file included from AXIS_CNC.c:16:0:
/usr/include/pthread.h:235:12: note: expected ‘void * __restrict__’ but argument is of type ‘int’
 extern int pthread_create (pthread_t *__restrict __newthread,
            ^

**Comment by i-am-unbekannt** [comment]
Hello MadaraV2492,

To better understand the issue you're facing, could you please provide more information? 

- What operating system are you trying to run the tool on?
- Is the error related to compilation or execution?
- Have you installed all the required dependencies?
- Is your system up to date?

By providing these details, I'll be able to assist you more effectively in troubleshooting the problem.

~ Unbekannt
