### ISSUE TITLE
How playload work

### ISSUE THREAD

**Issue by MadaraV2492** [i-am-unbekannt/AXIS#6]
hello waht os i need for payload ??

**Comment by i-am-unbekannt** [comment]
Hello MadaraV2492,

You can execute the payload on any Unix system. However, I recommend to load SSH or TELNET bots to the AXIS Botnet. This is the intended purpose of the Botnet.

Currently, I am working on other projects such as the Unbekannt Framework and an enhanced botnet with a web interface called "Orbital Cannon." In the future, I plan to update the AXIS Botnet and add a function that allows manual loading of bots. For now, you can refer to online resources to learn how to load SSH or TELNET bots into the botnet.

~ Unbekannt
